# Generated by Django 4.2.30 on 2026-05-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', models.TextField()),
                ('products_sold', models.CharField(default='500+', max_length=20)),
                ('happy_clients', models.CharField(default='200+', max_length=20)),
                ('delivery_area', models.CharField(default='Pan India', max_length=50)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('company_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Website Content',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours',
            field=models.TextField(blank=True),
        ),
    ]
