# Generated by Django 4.2.30 on 2026-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homecontent_sitesettings_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Company / Business Name')),
                ('website_type', models.CharField(choices=[('business', 'Business / Corporate'), ('ecommerce', 'E-Commerce / Online Store'), ('portfolio', 'Portfolio / Personal'), ('blog', 'Blog / News / Magazine'), ('landing', 'Landing Page'), ('other', 'Other')], max_length=20, verbose_name='Website Type')),
                ('pages_needed', models.PositiveIntegerField(default=5, verbose_name='Approx. Pages Needed')),
                ('need_development', models.BooleanField(default=True, verbose_name='Website Development')),
                ('need_maintenance', models.BooleanField(default=False, verbose_name='Annual Maintenance')),
                ('need_domain', models.BooleanField(default=False, verbose_name='Domain Registration')),
                ('need_seo', models.BooleanField(default=False, verbose_name='SEO Setup')),
                ('need_admin_panel', models.BooleanField(default=False, verbose_name='Admin / CMS Panel')),
                ('project_description', models.TextField(blank=True, verbose_name='Project Description')),
                ('budget_range', models.CharField(choices=[('under_10k', 'Under ₹10,000'), ('10k_20k', '₹10,000 – ₹20,000'), ('20k_40k', '₹20,000 – ₹40,000'), ('40k_plus', '₹40,000+'), ('discuss', "Let's Discuss")], default='discuss', max_length=20, verbose_name='Budget Range')),
                ('timeline', models.CharField(choices=[('asap', 'ASAP'), ('1_month', 'Within 1 Month'), ('3_month', 'Within 3 Months'), ('flexible', 'Flexible')], default='flexible', max_length=20, verbose_name='Preferred Timeline')),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'In Review'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=10, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes (private)')),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quoted Amount (₹)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
