# Generated by Django 4.2.30 on 2026-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Experience The Sound', help_text='Overlay title shown on the video screen', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline below the title', max_length=300)),
                ('video_file', models.FileField(blank=True, help_text='Upload an MP4 video (recommended: 1080p, max 50MB)', null=True, upload_to='experience/')),
                ('video_url', models.URLField(blank=True, help_text='OR paste a YouTube / direct MP4 URL instead of uploading')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Experience Video',
                'verbose_name_plural': 'Experience Video',
            },
        ),
        migrations.DeleteModel(
            name='QuoteRequest',
        ),
    ]
