# Generated by Django 4.2.30 on 2026-06-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='services_heading',
            field=models.CharField(default='Professional DJ, Sound & Lighting for Every Event', help_text='Big heading shown above the services carousel on the homepage', max_length=200),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='services_subtext',
            field=models.CharField(default='From weddings and corporate events to concerts and private parties — complete professional event production.', help_text='Short description shown beside the services heading', max_length=300),
        ),
    ]
